In [1]:
import sys
sys.path.append("..")

In [2]:
from datasets.tiflux import tickets
df_tickets = tickets()

2026-02-19 13:43:34.668 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-02-19 13:43:34.668 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager
2026-02-19 13:43:34.668 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-02-19 13:43:34,668 | INFO | datasets | Solicitado dataset tiflux.tickets
2026-02-19 13:43:34,668 | INFO | datasets | Iniciando carga | sistema=Tiflux | tabela=Tiflux_tb_Tickets | path=C:\Users\Israel Panazollo\Documents\AnalisesPy\plataforma_bi\data\staging\Tiflux\Tiflux_tb_Tickets.csv
2026-02-19 13:43:35,423 | INFO | datasets | Carga concluída | sistema=Tiflux | tabela=Tiflux_tb_Tickets | linhas=88952 | colunas=22 | tempo=0.755s

In [3]:
df_tickets.head()

,Id_ticket,Id_cliente,Cliente,Desc_ticket,Situacao,Mesa,Responsavel,Solicitado_por,Email_responsavel,Ultima_resposta,...,Catalogo_de_Servicos,Item,Criado_em,Data_1o_apontamento,Fechado_em,Avaliacao,SLA_atendido,Duracao_apontada,Tempo_total_fechamento,Link_chamado
0,7,64478,Grupo Voyzer,teste wpp,NaN,Help-Desk,David Zirbes,David Zirbes,david_zirbes@solarti.com.br,NaN,...,NaN,NaN,2020-06-22 10:35:00,2020-06-22 11:26:00,2020-06-22 11:29:00,NaN,Sim,0.0,0.907778,https://app.tiflux.com/v/tickets/7/basic_info
1,8,64478,Grupo Voyzer,teste 123,NaN,Help-Desk,David Zirbes,Eduardo Carniel,eduardo_carniel@solarti.com.br,NaN,...,NaN,NaN,2020-06-22 11:57:00,2020-06-22 13:43:00,2020-06-22 13:45:00,NaN,Sim,0.0,1.800833,https://app.tiflux.com/v/tickets/8/basic_info
2,9,64478,Grupo Voyzer,teste chamados,NaN,Help-Desk,David Zirbes,David Zirbes,david_zirbes@solarti.com.br,NaN,...,N/A2,Falha de acesso à rede,2020-07-08 16:34:00,2020-07-09 11:41:00,2020-07-09 11:44:00,NaN,Sim,0.0,5.465000,https://app.tiflux.com/v/tickets/9/basic_info
3,10,64478,Grupo Voyzer,[VPN]Instalar VPN,NaN,Help-Desk,Lucas Polidorio,David Zirbes,david_zirbes@solarti.com.br,NaN,...,N/A2,Atualização de Drivers,2020-07-09 11:05:00,2020-07-09 15:20:00,2020-07-09 16:12:00,NaN,Sim,0.0,5.115000,https://app.tiflux.com/v/tickets/10/basic_info
4,11,64478,Grupo Voyzer,teste,NaN,Help-Desk,David Zirbes,David Zirbes,david_zirbes@solarti.com.br,NaN,...,N/A2,Falha de acesso à rede,2020-07-17 14:32:00,2020-07-17 10:00:00,2020-07-17 14:47:00,NaN,Sim,26.0,0.255000,https://app.tiflux.com/v/tickets/11/basic_info

In [4]:
len(df_tickets)

88952

In [5]:
df_tickets["Situacao"].value_counts()

Situacao
Fechado      84158
Cancelado     2857
Aberto         880
Name: count, dtype: int64

In [6]:
df_tickets["Fechado_em"].isna().sum()

np.int64(880)

In [7]:
df_tickets[df_tickets["Fechado_em"].isna()][["Id_ticket", "Situacao", "Fechado_em"]].head()

       Id_ticket Situacao Fechado_em
51854      51905   Aberto        NaT
52502      52553   Aberto        NaT
52558      52609   Aberto        NaT
52782      52833   Aberto        NaT
52896      52947   Aberto        NaT

In [8]:
df_tickets["Fechado_em"].head()

0   2020-06-22 11:29:00
1   2020-06-22 13:45:00
2   2020-07-09 11:44:00
3   2020-07-09 16:12:00
4   2020-07-17 14:47:00
Name: Fechado_em, dtype: datetime64[ns]

In [18]:
import pandas as pd
caminho = "../data/staging/Tiflux/Tiflux_tb_Tickets.csv"
df = pd.read_csv(caminho)

In [19]:
len(df)

88952

In [20]:
df["Situacao"].value_counts()

Situacao
Fechado      84158
Cancelado     2857
Aberto         880
Name: count, dtype: int64

In [21]:
df["Fechado_em"].isna().sum()

np.int64(880)

In [28]:
df["Fechado_em"].head()

0    2020-06-22 11:29:00
1    2020-06-22 13:45:00
2    2020-07-09 11:44:00
3    2020-07-09 16:12:00
4    2020-07-17 14:47:00
Name: Fechado_em, dtype: object